version: '2'

services: 
  fswebsample:
    build: ./fsharp-kestrel-sample
    image: serilog-fsharp-kestrel-sample 
    ports:
      - 5001:5001      
  consoleapp:
    build: ./console-sample
    image: serilog-console-sample
    links:
      - websample
  websample:
    build: ./web-sample
    image: serilog-web-sample 
    ports:
      - 5000:5000
    